Repository elastic/rally-eventdata-track, pull requests merged in 2020-01, with the labels that each got.

#65 Remove obsolete create-index tasks
  eventdata/challenges/bulk-update.json
  eventdata/challenges/document_id_benchmark.json
  eventdata/challenges/frozen.json
  eventdata/challenges/large-shard-sizing.json
  eventdata/challenges/shard-size-on-disk.json
  eventdata/challenges/shard-sizing.json
Labels: cleanup

#67 Use number_of_shards instead of shard_count
  README.md
  eventdata/challenges/daily-log-volume-index.json
  eventdata/challenges/document_id_benchmark.json
  eventdata/challenges/large-shard-sizing.json
  eventdata/elasticlogs-index-template.json
Labels: cleanup

#71 Query more data for daily indices
  eventdata/challenges/daily-log-volume-index-and-query.json
  eventdata/runners/kibana_runner.py
  smoke-test.sh
Labels: bug

#73 Lower windows for queries
  eventdata/challenges/daily-log-volume-index-and-query.json
Labels: enhancement

#72 Use discover query in discover operation
  eventdata/operations/querying.json
Labels: bug

#70 Avoid more time-consuming calls
  eventdata/parameter_sources/elasticlogs_bulk_source.py
  eventdata/parameter_sources/randomevent.py
  eventdata/parameter_sources/timeutils.py
  tests/parameter_sources/elasticlogs_bulk_source_test.py
  tests/parameter_sources/randomevent_test.py
  tests/parameter_sources/timeutils_test.py
Labels: enhancement

#68 externalize time_period param in query challenge
  README.md
  eventdata/challenges/elasticlogs-querying.json
Labels: backport pending, enhancement

#78 Make hits optional
  eventdata/runners/kibana_runner.py
Labels: bug

#77 Expose additional meta-data for queries
  eventdata/challenges/daily-log-volume-index-and-query.json
Labels: enhancement

#76 Expose starting_point for daily indexing
  README.md
  eventdata/challenges/daily-log-volume-index.json
Labels: enhancement

#79 Use top-level took value for meta-data
  eventdata/runners/kibana_runner.py
  tests/runners/__init__.py
  tests/runners/kibana_runner_test.py
Labels: enhancement
